quarkus.application.name=ms-risk-mock-credit-evaluation
quarkus.application.version=1.0.0

quarkus.http.port=8081

# OpenAPI / Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
mp.openapi.extensions.smallrye.info.title=Risk Mock Service API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Microservicio mock para simulación de datos de riesgo crediticio

# CORS - solo acepta peticiones del orquestador (ambiente productivo)
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080

# Logging
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
